hmcts/et-pet-admin

app/admin/admin_offices.rb
app/assets/stylesheets/active_admin.scss
app/assets/stylesheets/et_offices_active_admin.scss
app/models/admin/office.rb
app/models/admin/office_post_code.rb
app/policies/admin/office_policy.rb
config/locales/en.yml

Admin page with basic offices info and their assigned postcodes.

Create the ET Offices page

---

app/models/admin/atos_file.rb
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Atos file proxy using username and password

Atos file proxy using username and password

---

app/admin/admin_acas_download_log.rb
app/models/admin/acas_download_log.rb
app/policies/admin/acas_download_log_policy.rb

ACAS Download logs can now be viewed if the user has permission

ACAS Download logs can now be viewed if the user has permission

---

.env
app/models/admin/user.rb
app/services/admin/users_import_service.rb
config/application.rb
config/environments/production.rb
config/initializers/devise.rb
lib/set_action_mailer_host.rb

User import now downcases email addres
User import now groups by password and role - caching the expensive calculations for both of these for the rest of the group - improving performance from about 40 seconds down to less than 5 (it was causing timeouts in development / staging)

User import now downcases email addres

---

app/admin/admin_users.rb

RST-1296 - Remove password hash, reset password token & unlock token from User show view

---

Dockerfile
awslogs.conf
expand_variables.sh
run.sh

Add Kibana logging (via @isherraikmo)

Add Kibana Logging

---

Dockerfile

Prevent secret key check failure during docker build

Prevent secret key check failure during docker build

---

Dockerfile
app/admin/admin_diversity_responses.rb
app/models/diversity_response.rb
app/policies/diversity_response_policy.rb

- RST-1234 - ADMIN - Added diversity responses tab to admin

Preparation for release 1.3.0

---

Dockerfile
app/admin/admin_office_post_codes.rb
app/models/office_post_code.rb
run.sh
supervisor.conf
supervisor_awslogs.conf

None
RST-1344 Case insensitive validation added for postcodes. Ensures no duplicates
RST-1344 Minor wording changes - now 'Office Postcodes'
- Logging changes - Setup supervisor to keep logging process alive

Preparation for release v1.3.1

---

app/admin/admin_users.rb
app/models/admin/user.rb
app/policies/admin/role_policy.rb
db/seeds.rb

* Admins can add new users with an email address, username, department, password and role.
* Users do not need to reset password to update a user
* Super users and admins can delete, change department and roles. Super users cannot see the admin role and cannot promote themselves.
**There is an accompanying migration in the API**

RST-1314: Manage Users via portal

---

lib/tasks/extract_data.rake

I had to patch `release/v1.5.0` so this PR will merge the additional merge back into develop otherwise develop will not be the most up-to-date branch.

Add patched v1.5.0 to develop

---

app/models/admin/user.rb
app/validators/username_validator.rb

Criteria:
* Username consists of 4 to 30 characters inclusive
* The username can only contain alphanumeric characters and underscores (_)
* The first character of the username must be an alphabetic character

RST1435: Add validation to username

---

Gemfile.lock

Updated rack to 2.0.6 due to vulnerability

Updated rack to 2.0.6 due to vulnerability

---

Gemfile.lock
config/initializers/active_storage.rb

Gemfile.lock missed from last commit
Added active storage patch for azure

Gemfile.lock missed from last commit

---

Gemfile
Gemfile.lock

Configured to use azure_env_secrets gem ready for azure

RST-1750 ADMIN (Azure) - Configure to use the azure_env_secrets gem

---

config/environments/production.rb

Removed asset prefix - were not gonna need it now

RST-1759 ADMIN (Azure) Asset configuration

---

README.md
config/initializers/sidekiq.rb

Sidekiq config now includes password

Sidekiq config now includes password

---

config/environments/production.rb

Log level is now controlled using RAILS_LOG_LEVEL in production

Log level is now controlled using RAILS_LOG_LEVEL in production

---

Dockerfile
azure-pipelines.yml

Add Azure Pipelines Devops Functionality

---

azure-pipelines.yml

Adding conditions to pipelines

---

Dockerfile
README.md
azure-pipelines.yml

ping.json fix and manual pipeline build

---

app/admin/admin_offices.rb

This PR allows offices to be edited (permissions allowing)
```
[ ] Yes
[X] No
```

RST-2008 - Allow offices to be edited

---

app/admin/admin_external_systems.rb

NA
This PR adds an 'export' toggle to the admin's external systems - allowing an external system to be disabled
```
[ ] Yes
[ ] No
```

Add export toggle to external systems

---

app/admin/admin_external_systems.rb
app/models/external_system.rb

external_systems json output added
```
[ ] Yes
[X] No
```

externa systems json output added

---

app/admin/admin_claims.rb
app/admin/admin_responses.rb
app/policies/export_policy.rb

RST-2156
Restricts access to the new export functionality
```
[ ] Yes
[X] No
```

RST-2156 restrict access to the export functionality

---

app/admin/admin_external_systems.rb

Bug fix - export queue was not editable
```
[ ] Yes
[X] No
```

Bug fix - export queue was not editable

---

app/admin/admin_claims.rb
app/admin/admin_exports.rb
app/models/export.rb
app/models/export_event.rb

RST-2197
This PR introduces changes in the claims and exports view to show the status of claims being exported to CCD
```
[ ] Yes
[X] No
```

Rst 2197 export states

---

azure-pipelines.yml

removing blob storage assets
```
[ ] Yes
[x] No
```

removing blob storage assets

---

.env
app/admin/admin_claims.rb

RST-2306
This PR improves the ccd_state column in the claims view to provide a link to the export for drilling down into errors
```
[ ] Yes
[ ] No
```

RST-2306 (CCD, ADMIN) - Export link

---

.env
.gitignore
Gemfile
README.md

RST-2425
This PR tweaks the environment to allow for easy running, developing and testing whilst the et_full_system is running
```
[ ] Yes
[X] No
```

Changes to allow running local version in full system environment

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/test.rb

RST-2144
This PR implements application insights
```
[ ] Yes
[X] No
```

Rst 2144 insights

---

app/admin/admin_commands.rb
app/models/command.rb
app/policies/command_policy.rb

RST-2761
This PR allows an administrator only to see commands recorded for diagnosis
```
[ ] Yes
[X] No
```

RST-2761 Claim routed to incorrect office

---

app/admin/admin_responses.rb
app/admin/admin_roles.rb
app/models/response.rb

https://tools.hmcts.net/jira/browse/RST-2889
This PR adds the files column to the et3 responses and adds some useful filters to the right hand side of the view
```
[ ] Yes
[X] No
```

RST-2889 - ET Admin dashboard - Add/amend filters to responses page

---

app/admin/admin_users.rb

RST-2713 Roles displayed in users list

---

app/admin/admin_claims.rb
app/admin/admin_responses.rb
app/admin/admin_uploaded_files.rb
app/models/response.rb
app/models/uploaded_file.rb
app/policies/response_policy.rb
app/policies/uploaded_file_policy.rb
app/services/admin/repair_response_service.rb

This PR adds functionality to repair a broken et3 response - it must be used alongside API changes with the same branch name
```
[ ] Yes
[X] No
```

RST-2905 Repair functionality

---

app/admin/admin_claims.rb

https://tools.hmcts.net/jira/browse/RST-2888
This PR removes unwanted filters from the claims page
```
[ ] Yes
[X] No
```

RST-2888 Removed filters from claims page

---

app/admin/admin_claims.rb

https://tools.hmcts.net/jira/browse/RST-2826
RST-2826 ET Admin - Amendments
```
[ ] Yes
[X] No
```

RST-2826 ET Admin - Amendments

---

app/admin/admin_uploaded_files.rb

JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RST-3063
RST-3063 Added ability to view and edit uploaded file import urls and keys
```
[ ] Yes
[X] No
```

RST-3063 Added ability to view and edit uploaded file import urls and keys

---

app/admin/admin_responses.rb
app/models/uploaded_file.rb

https://tools.hmcts.net/jira/browse/RST-2929
RST-2929 Response file duplication
```
[ ] Yes
[X] No
```

RST-2929 Response file duplication

---

azure-pipelines.yml

Changed pool for push and deploy

---

app/models/claim.rb

RST-3306 Claims not exported to ccd query fixed

---

app/mailers/application_mailer.rb
config/application.rb

HOTFIX Corrected mail sender to work with new sendgrid account

---

app/admin/admin_et3_reconciliation_report.rb
app/models/et3_reconciliation_report.rb

(RST-3448) Added validation to report form

---

app/admin/admin_claims.rb
app/admin/admin_uploaded_files.rb
app/models/uploaded_file.rb

RST-3855 Added Ability to see the 'file_scope' in uploaded files

---

app/admin/admin_claims.rb

This PR modifies the CSV output from the claims admin page to include the CCD reference number
```
[ ] Yes
[ ] No
```

RST-4117 ET Admin - Additional field on csv output

---

README.md
app/controllers/application_controller.rb
app/views/static_pages/maintenance.html.erb
config/application.rb

RST-4218 Maintenance page

---

config/database.yml

RST-4279 All external values in database.yml now quoted

---

app/admin/admin_claims.rb
app/admin/admin_default_office_claims.rb
app/admin/admin_responses.rb
app/admin/admin_uploaded_files.rb
config/application.rb
config/storage.yml

RST-4686 New file upload system

---

Dockerfile.dev
config/application.rb
config/environments/development.rb
config/initializers/sidekiq.rb

Redis now more configurable
RST-4439
```
[ ] Yes
[X] No
```

Changes for use with skaffold

---

config/environments/production.rb

(RST-5112) Uglifier only used if present in production.rb

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

(RST-5651) Corrected API urls

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

(RST-5651) Fixed api url and enabled debug logging

---

Gemfile.lock
charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

Rst 5651 Updated iodine

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

(RST-5651) Fixed api urls

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

(RST-5914) Correct CCD_UI_BASE_URL

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

(RST-5976) Switch to using new app insights

---

charts/et-pet-admin/Chart.yaml
charts/et-pet-admin/values.yaml

Re configured chart values to share the api azure storage credentials

---

config/environments/production.rb

(RST-6145) Prevented caching of any pages

---

Gemfile.lock

(RST-6290) Upgraded nokogiri (security issue)

---

app/policies/claimant_policy.rb

(RST-6570) Fixed bug preventing deletion of claimants
